### ISSUE TITLE
No Camera Streaming section therefore no 'Camera' dropdown - failed to initialize camera

### ISSUE THREAD

**Issue by troyboy27** [rzeldent/esp32cam-rtsp#113]
![Untitled 5](https://github.com/rzeldent/esp32cam-rtsp/assets/9325869/41cd78ec-39f0-4a13-90d0-5701067d68a3)

I do not have the Camera field dropdown.

**Comment by rzeldent** [comment]
Hi Troyboy,

I guess you mean the camera config as mentioned in the documentation:
![image](https://github.com/rzeldent/esp32cam-rtsp/assets/7620231/6ac700ce-7f23-43f8-9285-f6bf3f4cf177)

If so, this is correct. This has been removed. The reason for that is that before only one ESP32 type was supported but now also the ESP32-S2 and ESP32-S3. Because the toolchain is different this could not be continued.

However, there is a list to better identify the type of camera so you can select the correct one. This can be done by uncommenting the ```default_envs``` in the ```platformio.ini``` file for your board type...

**Comment by troyboy27** [comment]
Hi- I cannot select anything since I don't have a drop-down as indicated in
the documentation. The config for every camera is compiled and uploaded to
the chip. I'm not sure I'm following.

**Comment by rzeldent** [comment]
You have to select the right camera, using the Platformio menu.
