### ISSUE TITLE
What is the IP? ESP32-CAM

### ISSUE THREAD

**Issue by AntDX316** [rzeldent/esp32cam-rtsp#126]
What is the IP? ESP32-CAM

Nothing pops up to configure for the IP.

**Comment by rzeldent** [comment]
Hi Ant,

After connecting to the Access Point created by the ESP-CAM (using the SSID and password in the documentation), there should be a landing page. This is browser and sometimes connection dependent.

Otherwise the IP is 192.168.4.1 I suggest also to have the serial monitor running if you encounter problems.
