### ISSUE TITLE
Not saving SSID and pass.

### ISSUE THREAD

**Issue by ChuckRockTheReal** [rzeldent/esp32cam-rtsp#60]
I've uploaded to the esp32cam, login in to the AP, I change the SSID and password for my network, apply the new setting. It shows them in the log, but it just goes back to the default and does not request the ip reservation I had created in my router.

any ideas?

**Comment by rzeldent** [comment]
Hi Chuck,

Most of the time this is because no connection could be made with the provided credentials. Then it defaults back to AP mode.
Another possibility is that the SSID is on 5Ghz (ESP32 only supports 2.4Ghz) so no connection could be made...

Let me know if this helps/works now...

Kind regards
Rene

**Comment by alior101** [comment]
I had the same issues, then I looked carefully at the logs and saw a space added to my AP SSID name... It could be from the html config page. Anyway, making sure there is no spaces in the text box where I put the SSID name and making sure that the SSID is correct in the logs fixed the issue for me.. Good luck..

**Comment by rzeldent** [comment]
Chuck? Any progress?
